services:
  # --- DEVELOPMENT SERVICE ---
  api-dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile\
    image: mern-auth-service:dev
    container_name: mern-api-dev
    ports:
      - '5501:5501'
    volumes:
      - .:/app
      - /app/node_modules # Ensures container modules stay inside the container
    environment:
      - NODE_ENV=dev
    env_file:
      - .env.dev
    depends_on:
      db-project2:
        condition: service_healthy # Wait for DB to be "Ready", not just "Started"

  # --- PRODUCTION SERVICE ---
  api-prod:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: mern-auth-service:prod
    container_name: mern-api-prod
    ports:
      - '5500:5500'
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    depends_on:
      db-project2:
        condition: service_healthy

  db-project2:
    image: postgres:17
    container_name: mern-auth-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - mern_auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mern_auth_pgdata:
